# Generated by Django 4.2.7 on 2023-11-28 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_like', '0001_initial'),
        ('coffee_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='coffee_likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='coffee_like.like'),
        ),
    ]
